name: mukrata_sau_app
description: "A new Flutter project."

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
